name: task-3-workflow
run-name: Task 3 workflow
on:
  pull_request:
    paths:
      - "desktop-app/**/*.ts"
      - "desktop-app/package.json"
      - "desktop-app/tsconfig.*"
      - "desktop-app/vite"

defaults:
  run:
    working-directory: desktop-app
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: desktop-app
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
