name: task 4 workflow
on: 
    push: 
      paths: 
        - desktop-app/**.ts
    # event - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./desktop-app
    
         # system - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: desktop-app/package-lock.json

      - run: npm ci

      - run: npm run build
      - run: npm test
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: failed-tests
          path: |
            desktop-app/test-results/**

      
      
